# Generated by Django 4.2.24 on 2026-02-22 16:59

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_slide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=store.models.Slide.get_unique_filename, validators=[store.models.Slide.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=255),
        ),
        migrations.AlterField(
            model_name='slide',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=store.models.Slide.get_unique_filename, validators=[store.models.Slide.validate_video_size]),
        ),
    ]
