# Generated by Django 4.2.24 on 2026-02-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_testimonial_alter_products_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('pinterest', models.CharField(blank=True, max_length=255, null=True)),
                ('phone1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number 1')),
                ('phone2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number 2')),
                ('phone3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number 3')),
                ('email1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email 1')),
                ('email2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email 2')),
                ('email3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email 3')),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Settings',
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameModel(
            old_name='Testimonial',
            new_name='Review',
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Reviews'},
        ),
    ]
