# Generated by Django 4.2.24 on 2026-02-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_settings_rename_testimonial_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
