# Generated by Django 4.2.24 on 2026-03-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_settings_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='youtube',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
