version: "3.8"

services:
  amra-app:
    container_name: amra
    restart: always
    image: amra
    # image: $IMAGE_TAG
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static
  
  db:
    image: postgres:15
    container_name: amra_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

volumes:
  media: {}
  static: {}
  postgres_data: {}